name: Build

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Check out the repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0

      - name: 🛠️ Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: 📦 Install dependencies
        run: go mod download

      - name: 🧪 Test
        run: go test -v ./...

      - name: 🧹 Check formatting
        run: |
          go fmt ./...
          git diff --exit-code
